// flow-typed signature: b0fb119848b9c65aa86851c30bce637b
// flow-typed version: <<STUB>>/bbcode-to-react_v^0.2.9/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bbcode-to-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bbcode-to-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bbcode-to-react/dist/bbcode-to-react' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/dist/bbcode-to-react.min' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/constants' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/index' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/parser' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/renderer' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tag' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/center' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/code' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/color' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/hr' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/image' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/index' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/item' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/link' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/list' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/quote' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/right' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/simple' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/lib/tags/size' {
  declare module.exports: any;
}

declare module 'bbcode-to-react/tonic-example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bbcode-to-react/dist/bbcode-to-react.js' {
  declare module.exports: $Exports<'bbcode-to-react/dist/bbcode-to-react'>;
}
declare module 'bbcode-to-react/dist/bbcode-to-react.min.js' {
  declare module.exports: $Exports<'bbcode-to-react/dist/bbcode-to-react.min'>;
}
declare module 'bbcode-to-react/lib/constants.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/constants'>;
}
declare module 'bbcode-to-react/lib/index.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/index'>;
}
declare module 'bbcode-to-react/lib/parser.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/parser'>;
}
declare module 'bbcode-to-react/lib/renderer.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/renderer'>;
}
declare module 'bbcode-to-react/lib/tag.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tag'>;
}
declare module 'bbcode-to-react/lib/tags/center.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/center'>;
}
declare module 'bbcode-to-react/lib/tags/code.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/code'>;
}
declare module 'bbcode-to-react/lib/tags/color.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/color'>;
}
declare module 'bbcode-to-react/lib/tags/hr.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/hr'>;
}
declare module 'bbcode-to-react/lib/tags/image.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/image'>;
}
declare module 'bbcode-to-react/lib/tags/index.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/index'>;
}
declare module 'bbcode-to-react/lib/tags/item.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/item'>;
}
declare module 'bbcode-to-react/lib/tags/link.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/link'>;
}
declare module 'bbcode-to-react/lib/tags/list.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/list'>;
}
declare module 'bbcode-to-react/lib/tags/quote.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/quote'>;
}
declare module 'bbcode-to-react/lib/tags/right.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/right'>;
}
declare module 'bbcode-to-react/lib/tags/simple.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/simple'>;
}
declare module 'bbcode-to-react/lib/tags/size.js' {
  declare module.exports: $Exports<'bbcode-to-react/lib/tags/size'>;
}
declare module 'bbcode-to-react/tonic-example.js' {
  declare module.exports: $Exports<'bbcode-to-react/tonic-example'>;
}
