// flow-typed signature: 8686b43a245985a145c250c7bcd42242
// flow-typed version: <<STUB>>/js-bbcode-parser_v^2.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-bbcode-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-bbcode-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-bbcode-parser/parser' {
  declare module.exports: any;
}

declare module 'js-bbcode-parser/src/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-bbcode-parser/parser.js' {
  declare module.exports: $Exports<'js-bbcode-parser/parser'>;
}
declare module 'js-bbcode-parser/src/parser.js' {
  declare module.exports: $Exports<'js-bbcode-parser/src/parser'>;
}
